name: Pipeline
on: 
  workflow_dispatch:
  #push:
  #  branches: 
  #    - main
jobs:
  e2e-tests:
    runs-on: ubuntu-latest
    
    environment: staging
    steps:    
      #install packages      
      - name: Run echo
        run: echo hello

      - name: Run echo2
        run: echo hello2
        run: echo ${{ secrets.USERNAME}}
          