name: Pipeline
on: 
  #workflow_dispatch:
  
  #push:
  #  branches: 
  #    - main
  
  workflow_dispatch:
    inputs:
      environment:
        description: 'Choose the environment'
        required: true
        type: choice
        options:
          - uat
          - staging

jobs:
  e2e-tests:
    runs-on: ubuntu-latest            
    environment:  ${{ github.event.inputs.environment }}
    steps:    
      #install packages      
      - name: Choosen environment
        run: echo ${{ github.event.inputs.environment }}

      - name: Run echo
        run: echo hello
        
      - name: Run echo2        
        run: echo ${{ secrets.USERNAME}}
          